2021-08-05 11:16:42,333 - app - INFO -API started Successfully
2021-08-05 11:16:42,333 - app - INFO -7197
2021-08-05 11:16:42,333 - app - INFO -runing ...
2021-08-05 11:16:42,348 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 11:18:03,260 - app - INFO -API started Successfully
2021-08-05 11:18:03,263 - app - INFO -7197
2021-08-05 11:18:03,263 - app - INFO -runing ...
2021-08-05 11:18:03,277 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 11:21:21,735 - app - INFO -instance Request Initiated
2021-08-05 11:21:21,736 - app - ERROR -Exception while submitting file processing Request
Traceback (most recent call last):
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\wrappers.py", line 74, in get_json
    rv = json.loads(data)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 205, in loads
    return _json.loads(s, **kwargs)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 37, in get
    return_status, result = fp.run(request, "select")
  File "C:\Users\ramu.s\flask_api\middleware\AtmFlow.py", line 16, in run
    payload=request.json
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\wrappers.py", line 82, in get_json
    rv = self.on_json_loading_failed(e)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\wrappers.py", line 108, in on_json_loading_failed
    raise BadRequest()
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2021-08-05 11:21:21,807 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:21:21] "GET /atms HTTP/1.1" 500 -
2021-08-05 11:25:16,759 - app - INFO -API started Successfully
2021-08-05 11:25:16,759 - app - INFO -7197
2021-08-05 11:25:16,759 - app - INFO -runing ...
2021-08-05 11:25:16,775 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 11:25:22,146 - app - INFO -instance Request Initiated
2021-08-05 11:25:22,217 - app - ERROR -Exception while submitting feedback
Traceback (most recent call last):
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: atms

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ramu.s\flask_api\middleware\AtmFlow.py", line 21, in run
    db_res=db_obj.fetch_atmdata()
  File "C:\Users\ramu.s\flask_api\resources\atm_data_process.py", line 32, in fetch_atmdata
    tbl_data=conn.execute(select_sql)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1178, in _execute_text
    parameters,
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: atms
[SQL: select * from atms order by id]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2021-08-05 11:25:22,321 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:25:22] "GET /atms HTTP/1.1" 500 -
2021-08-05 11:38:46,445 - app - INFO -API started Successfully
2021-08-05 11:38:46,445 - app - INFO -7197
2021-08-05 11:38:46,445 - app - INFO -runing ...
2021-08-05 11:38:46,460 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 11:38:53,156 - app - INFO -instance Request Initiated
2021-08-05 11:38:53,166 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:38:53] "GET /atms HTTP/1.1" 200 -
2021-08-05 11:40:40,133 - app - INFO -API started Successfully
2021-08-05 11:40:40,133 - app - INFO -7197
2021-08-05 11:40:40,133 - app - INFO -runing ...
2021-08-05 11:40:40,149 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 11:41:04,919 - app - INFO -instance Request Initiated
2021-08-05 11:41:04,928 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:41:04] "GET /atms HTTP/1.1" 200 -
2021-08-05 11:44:30,974 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:44:30] "GET / HTTP/1.1" 200 -
2021-08-05 11:44:39,670 - app - INFO -instance Request Initiated
2021-08-05 11:44:48,329 - app - INFO -instance Request Initiated
2021-08-05 11:45:31,392 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:45:31] "GET /atms HTTP/1.1" 200 -
2021-08-05 11:45:31,393 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:45:31] "GET /atms HTTP/1.1" 200 -
2021-08-05 11:45:31,744 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:45:31] "GET /favicon.ico HTTP/1.1" 404 -
2021-08-05 11:45:42,258 - app - INFO -API started Successfully
2021-08-05 11:45:42,274 - app - INFO -7197
2021-08-05 11:45:42,274 - app - INFO -runing ...
2021-08-05 11:45:42,274 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 11:45:55,607 - app - INFO -instance Request Initiated
2021-08-05 11:45:55,616 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:45:55] "GET /atms HTTP/1.1" 200 -
2021-08-05 11:47:47,003 - app - INFO -API started Successfully
2021-08-05 11:47:47,003 - app - INFO -7197
2021-08-05 11:47:47,003 - app - INFO -runing ...
2021-08-05 11:47:47,019 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 11:47:56,993 - app - INFO -instance Request Initiated
2021-08-05 11:47:57,003 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:47:57] "GET /atms HTTP/1.1" 200 -
2021-08-05 11:49:30,493 - app - INFO -API started Successfully
2021-08-05 11:49:30,495 - app - INFO -7197
2021-08-05 11:49:30,498 - app - INFO -runing ...
2021-08-05 11:49:30,509 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 11:49:36,317 - app - INFO -instance Request Initiated
2021-08-05 11:49:36,327 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 11:49:36] "GET /atms HTTP/1.1" 200 -
2021-08-05 12:01:11,095 - app - INFO -API started Successfully
2021-08-05 12:01:11,095 - app - INFO -7197
2021-08-05 12:01:11,095 - app - INFO -runing ...
2021-08-05 12:01:11,113 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:01:15,838 - app - INFO -instance Request Initiated
2021-08-05 12:01:15,852 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:01:15] "GET /atms HTTP/1.1" 200 -
2021-08-05 12:02:23,185 - app - INFO -instance Request Initiated
2021-08-05 12:02:23,198 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:02:23] "GET /atms HTTP/1.1" 200 -
2021-08-05 12:10:40,877 - app - INFO -instance Request Initiated
2021-08-05 12:10:40,963 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:10:40] "POST /atms HTTP/1.1" 200 -
2021-08-05 12:11:19,293 - app - INFO -instance Request Initiated
2021-08-05 12:11:19,300 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:11:19] "GET /atms HTTP/1.1" 200 -
2021-08-05 12:11:29,243 - app - INFO -instance Request Initiated
2021-08-05 12:11:29,258 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:11:29] "GET /atms HTTP/1.1" 200 -
2021-08-05 12:14:08,754 - app - INFO -instance Request Initiated
2021-08-05 12:14:08,755 - app - ERROR -Exception while submitting feedback
Traceback (most recent call last):
  File "C:\Users\ramu.s\flask_api\middleware\AtmFlow.py", line 44, in run
    db_obj.update_atmdata(payload)
TypeError: update_atmdata() missing 1 required positional argument: 'record'
2021-08-05 12:14:08,758 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:14:08] "PUT /atms HTTP/1.1" 500 -
2021-08-05 12:17:41,657 - app - INFO -API started Successfully
2021-08-05 12:17:41,664 - app - INFO -7197
2021-08-05 12:17:41,665 - app - INFO -runing ...
2021-08-05 12:17:41,676 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:17:51,264 - app - INFO -instance Request Initiated
2021-08-05 12:17:51,356 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:17:51] "PUT /atms HTTP/1.1" 200 -
2021-08-05 12:18:03,278 - app - INFO -instance Request Initiated
2021-08-05 12:18:03,288 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:18:03] "GET /atms HTTP/1.1" 200 -
2021-08-05 12:18:42,045 - app - INFO -instance Request Initiated
2021-08-05 12:18:42,144 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:18:42] "DELETE /atms HTTP/1.1" 200 -
2021-08-05 12:18:46,784 - app - INFO -instance Request Initiated
2021-08-05 12:18:46,797 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:18:46] "GET /atms HTTP/1.1" 200 -
2021-08-05 12:35:11,592 - app - INFO -API started Successfully
2021-08-05 12:35:11,596 - app - INFO -7197
2021-08-05 12:35:11,596 - app - INFO -runing ...
2021-08-05 12:35:11,608 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:35:39,897 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:35:39] "GET /login HTTP/1.1" 200 -
2021-08-05 12:36:38,727 - app - INFO -API started Successfully
2021-08-05 12:36:38,727 - app - INFO -7197
2021-08-05 12:36:38,727 - app - INFO -runing ...
2021-08-05 12:36:38,748 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:36:50,441 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:36:50] "GET /login HTTP/1.1" 200 -
2021-08-05 12:39:04,988 - app - INFO -API started Successfully
2021-08-05 12:39:04,996 - app - INFO -7197
2021-08-05 12:39:04,996 - app - INFO -runing ...
2021-08-05 12:39:05,008 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:39:15,639 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:39:15] "GET /logins HTTP/1.1" 200 -
2021-08-05 12:48:48,669 - app - INFO -API started Successfully
2021-08-05 12:48:48,669 - app - INFO -7197
2021-08-05 12:48:48,669 - app - INFO -runing ...
2021-08-05 12:48:48,684 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:48:54,705 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:48:54] "GET /logins HTTP/1.1" 200 -
2021-08-05 12:49:05,652 - app - INFO -instance Request Initiated
2021-08-05 12:49:05,661 - app - ERROR -Exception while submitting feedback
Traceback (most recent call last):
  File "C:\Users\ramu.s\flask_api\middleware\AtmFlow.py", line 63, in run
    res=db_obj.authenticate()
TypeError: authenticate() missing 2 required positional arguments: 'username' and 'password'
2021-08-05 12:49:05,662 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:49:05] "POST /login HTTP/1.1" 500 -
2021-08-05 12:50:46,110 - app - INFO -API started Successfully
2021-08-05 12:50:46,110 - app - INFO -7197
2021-08-05 12:50:46,125 - app - INFO -runing ...
2021-08-05 12:50:46,125 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:51:06,363 - app - INFO -instance Request Initiated
2021-08-05 12:51:06,374 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:51:06] "POST /login HTTP/1.1" 200 -
2021-08-05 12:51:57,436 - app - INFO -API started Successfully
2021-08-05 12:51:57,439 - app - INFO -7197
2021-08-05 12:51:57,439 - app - INFO -runing ...
2021-08-05 12:51:57,449 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:52:09,351 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:52:09] "GET /login HTTP/1.1" 404 -
2021-08-05 12:52:42,670 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:52:42] "GET /login HTTP/1.1" 404 -
2021-08-05 12:52:50,913 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:52:50] "GET /favicon.ico HTTP/1.1" 404 -
2021-08-05 12:52:56,749 - app - INFO -API started Successfully
2021-08-05 12:52:56,752 - app - INFO -7197
2021-08-05 12:52:56,753 - app - INFO -runing ...
2021-08-05 12:52:56,763 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:53:03,575 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:53:03] "GET /login HTTP/1.1" 404 -
2021-08-05 12:53:28,644 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:53:28] "GET /logins HTTP/1.1" 200 -
2021-08-05 12:53:37,573 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:53:37] "POST /login HTTP/1.1" 404 -
2021-08-05 12:56:10,813 - app - INFO -API started Successfully
2021-08-05 12:56:10,816 - app - INFO -7197
2021-08-05 12:56:10,817 - app - INFO -runing ...
2021-08-05 12:56:10,826 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:56:35,026 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:56:35] "GET /login HTTP/1.1" 404 -
2021-08-05 12:56:40,602 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:56:40] "GET /logins HTTP/1.1" 200 -
2021-08-05 12:56:48,901 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:56:48] "POST /login HTTP/1.1" 404 -
2021-08-05 12:57:33,251 - app - INFO -API started Successfully
2021-08-05 12:57:33,251 - app - INFO -7197
2021-08-05 12:57:33,251 - app - INFO -runing ...
2021-08-05 12:57:33,266 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:58:01,604 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:58:01] "GET /login HTTP/1.1" 200 -
2021-08-05 12:58:09,012 - app - INFO -instance Request Initiated
2021-08-05 12:58:09,024 - flask.app - ERROR -Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 127, in login
    session['user'] = username
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\local.py", line 351, in __setitem__
    self._get_current_object()[key] = value
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\sessions.py", line 101, in _fail
    raise RuntimeError('The session is unavailable because no secret '
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
2021-08-05 12:58:09,152 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:58:09] "POST /login HTTP/1.1" 500 -
2021-08-05 12:59:30,625 - app - INFO -API started Successfully
2021-08-05 12:59:30,625 - app - INFO -7197
2021-08-05 12:59:30,625 - app - INFO -runing ...
2021-08-05 12:59:30,641 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 12:59:46,786 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:59:46] "GET /login HTTP/1.1" 200 -
2021-08-05 12:59:54,391 - app - INFO -instance Request Initiated
2021-08-05 12:59:54,550 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:59:54] "POST /login HTTP/1.1" 302 -
2021-08-05 12:59:54,555 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 12:59:54] "GET /dashboard HTTP/1.1" 200 -
2021-08-05 15:53:07,163 - app - INFO -API started Successfully
2021-08-05 15:53:07,167 - app - INFO -7197
2021-08-05 15:53:07,167 - app - INFO -runing ...
2021-08-05 15:53:07,181 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 15:53:17,798 - app - INFO -instance Request Initiated
2021-08-05 15:53:17,827 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 15:53:17] "GET /atms HTTP/1.1" 200 -
2021-08-05 15:55:41,128 - app - INFO -instance Request Initiated
2021-08-05 15:55:41,329 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 15:55:41] "POST /atms HTTP/1.1" 200 -
2021-08-05 15:55:47,184 - app - INFO -instance Request Initiated
2021-08-05 15:55:47,188 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 15:55:47] "GET /atms HTTP/1.1" 200 -
2021-08-05 15:56:22,185 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 15:56:22] "GET /logins HTTP/1.1" 404 -
2021-08-05 15:56:27,017 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 15:56:27] "GET /login HTTP/1.1" 200 -
2021-08-05 15:56:36,431 - app - INFO -instance Request Initiated
2021-08-05 15:56:36,436 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 15:56:36] "POST /login HTTP/1.1" 302 -
2021-08-05 15:56:36,742 - app - INFO -instance Request Initiated
2021-08-05 15:56:36,772 - flask.app - ERROR -Exception on /dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 134, in dashboard
    return render_template("dashboard.html",rest_list = rest_list)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ramu.s\flask_api\templates\dashboard.html", line 9, in top-level template code
    {% for d in rest_list.items() %}
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'items'
2021-08-05 15:56:36,839 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 15:56:36] "GET /dashboard HTTP/1.1" 500 -
2021-08-05 15:57:26,508 - app - INFO -API started Successfully
2021-08-05 15:57:26,515 - app - INFO -7197
2021-08-05 15:57:26,516 - app - INFO -runing ...
2021-08-05 15:57:26,527 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 15:57:31,960 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 15:57:31] "GET /login HTTP/1.1" 200 -
2021-08-05 15:57:53,313 - app - INFO -instance Request Initiated
2021-08-05 15:57:53,341 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 15:57:53] "POST /login HTTP/1.1" 302 -
2021-08-05 15:57:53,353 - app - INFO -instance Request Initiated
2021-08-05 15:57:53,364 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 15:57:53] "GET /dashboard HTTP/1.1" 200 -
2021-08-05 15:59:54,826 - app - INFO -API started Successfully
2021-08-05 15:59:54,828 - app - INFO -7197
2021-08-05 15:59:54,828 - app - INFO -runing ...
2021-08-05 15:59:54,842 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 16:00:15,258 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 16:00:15] "GET /dashboard HTTP/1.1" 200 -
2021-08-05 16:00:24,092 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 16:00:24] "GET /login HTTP/1.1" 200 -
2021-08-05 16:00:34,520 - app - INFO -instance Request Initiated
2021-08-05 16:00:34,547 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 16:00:34] "POST /login HTTP/1.1" 302 -
2021-08-05 16:00:34,827 - app - INFO -instance Request Initiated
2021-08-05 16:00:34,843 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 16:00:34] "GET /dashboard HTTP/1.1" 200 -
2021-08-05 16:01:20,334 - app - INFO -instance Request Initiated
2021-08-05 16:01:20,339 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 16:01:20] "GET /dashboard HTTP/1.1" 200 -
2021-08-05 16:01:31,337 - app - INFO -API started Successfully
2021-08-05 16:01:31,341 - app - INFO -7197
2021-08-05 16:01:31,342 - app - INFO -runing ...
2021-08-05 16:01:31,354 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 16:01:51,989 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 16:01:51] "GET /login HTTP/1.1" 200 -
2021-08-05 16:01:59,513 - app - INFO -instance Request Initiated
2021-08-05 16:01:59,539 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 16:01:59] "POST /login HTTP/1.1" 302 -
2021-08-05 16:01:59,551 - app - INFO -instance Request Initiated
2021-08-05 16:01:59,569 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 16:01:59] "GET /dashboard HTTP/1.1" 200 -
2021-08-05 17:59:01,329 - app - INFO -API started Successfully
2021-08-05 17:59:01,329 - app - INFO -7197
2021-08-05 17:59:01,329 - app - INFO -runing ...
2021-08-05 17:59:01,345 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 17:59:18,577 - app - INFO -instance Request Initiated
2021-08-05 17:59:18,578 - app - ERROR -Exception while submitting  processing Request
Traceback (most recent call last):
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\wrappers.py", line 74, in get_json
    rv = json.loads(data)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\json\__init__.py", line 205, in loads
    return _json.loads(s, **kwargs)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 39, in get
    payload=request.json
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\wrappers.py", line 47, in json
    return self.get_json()
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\wrappers.py", line 82, in get_json
    rv = self.on_json_loading_failed(e)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\wrappers.py", line 108, in on_json_loading_failed
    raise BadRequest()
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2021-08-05 17:59:18,591 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 17:59:18] "GET /atms HTTP/1.1" 500 -
2021-08-05 18:02:17,384 - app - INFO -API started Successfully
2021-08-05 18:02:17,384 - app - INFO -7197
2021-08-05 18:02:17,384 - app - INFO -runing ...
2021-08-05 18:02:17,400 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 18:02:22,640 - app - INFO -instance Request Initiated
2021-08-05 18:02:22,650 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:02:22] "GET /atms HTTP/1.1" 200 -
2021-08-05 18:03:28,273 - app - INFO -instance Request Initiated
2021-08-05 18:03:28,275 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:03:28] "GET /atms HTTP/1.1" 200 -
2021-08-05 18:03:45,089 - app - INFO -instance Request Initiated
2021-08-05 18:03:45,198 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:03:45] "DELETE /atms HTTP/1.1" 200 -
2021-08-05 18:04:58,589 - app - INFO -instance Request Initiated
2021-08-05 18:04:58,674 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:04:58] "POST /atms HTTP/1.1" 200 -
2021-08-05 18:05:07,497 - app - INFO -instance Request Initiated
2021-08-05 18:05:07,499 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:05:07] "GET /atms HTTP/1.1" 200 -
2021-08-05 18:06:41,214 - app - INFO -instance Request Initiated
2021-08-05 18:06:41,321 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:06:41] "PUT /atms HTTP/1.1" 200 -
2021-08-05 18:07:01,320 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:07:01] "GET /login HTTP/1.1" 200 -
2021-08-05 18:07:08,573 - app - INFO -instance Request Initiated
2021-08-05 18:07:08,577 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:07:08] "POST /login HTTP/1.1" 302 -
2021-08-05 18:07:08,582 - app - INFO -instance Request Initiated
2021-08-05 18:07:08,587 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:07:08] "GET /dashboard HTTP/1.1" 200 -
2021-08-05 18:09:03,978 - app - INFO -instance Request Initiated
2021-08-05 18:09:04,090 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:09:04] "PUT /atms HTTP/1.1" 200 -
2021-08-05 18:09:10,138 - app - INFO -instance Request Initiated
2021-08-05 18:09:10,142 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:09:10] "GET /atms HTTP/1.1" 200 -
2021-08-05 18:09:24,764 - app - INFO -instance Request Initiated
2021-08-05 18:09:24,768 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:09:24] "GET /dashboard HTTP/1.1" 200 -
2021-08-05 18:09:50,108 - app - INFO -instance Request Initiated
2021-08-05 18:09:50,111 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:09:50] "GET /atms HTTP/1.1" 200 -
2021-08-05 18:12:27,680 - app - INFO -API started Successfully
2021-08-05 18:12:27,680 - app - INFO -7197
2021-08-05 18:12:27,680 - app - INFO -runing ...
2021-08-05 18:12:27,695 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 18:12:54,397 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:12:54] "GET /login HTTP/1.1" 200 -
2021-08-05 18:12:59,273 - app - INFO -instance Request Initiated
2021-08-05 18:12:59,285 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:12:59] "POST /login HTTP/1.1" 302 -
2021-08-05 18:12:59,289 - app - INFO -instance Request Initiated
2021-08-05 18:12:59,291 - flask.app - ERROR -Exception on /dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ramu.s\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 129, in dashboard
    res_dict=result_dict.copy(deep=True)
TypeError: copy() takes no keyword arguments
2021-08-05 18:12:59,296 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:12:59] "GET /dashboard HTTP/1.1" 500 -
2021-08-05 18:13:52,442 - app - INFO -API started Successfully
2021-08-05 18:13:52,457 - app - INFO -7197
2021-08-05 18:13:52,457 - app - INFO -runing ...
2021-08-05 18:13:52,473 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 18:13:55,042 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:13:55] "GET /login HTTP/1.1" 200 -
2021-08-05 18:14:05,505 - app - INFO -instance Request Initiated
2021-08-05 18:14:05,521 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:14:05] "POST /login HTTP/1.1" 302 -
2021-08-05 18:14:05,528 - app - INFO -instance Request Initiated
2021-08-05 18:14:05,535 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 18:14:05] "GET /dashboard HTTP/1.1" 200 -
2021-08-05 19:56:53,973 - app - INFO -API started Successfully
2021-08-05 19:56:53,976 - app - INFO -7197
2021-08-05 19:56:53,977 - app - INFO -runing ...
2021-08-05 19:56:53,989 - werkzeug - INFO - * Running on http://0.0.0.0:7197/ (Press CTRL+C to quit)
2021-08-05 19:56:55,232 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 19:56:55] "GET /login HTTP/1.1" 200 -
2021-08-05 19:57:54,694 - app - INFO -instance Request Initiated
2021-08-05 19:57:54,705 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 19:57:54] "POST /login HTTP/1.1" 302 -
2021-08-05 19:57:54,709 - app - INFO -instance Request Initiated
2021-08-05 19:57:54,715 - werkzeug - INFO -127.0.0.1 - - [05/Aug/2021 19:57:54] "GET /dashboard HTTP/1.1" 200 -
